/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import {AuthTokenRole} from 'parabol-client/types/constEnums'

declare module 'zapatos/custom' {
  export type PgAuthTokenRoleDomain = AuthTokenRole.SUPER_USER;  // replace with your custom type or interface as desired
}
