/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import AuthIdentity from '../../../database/types/AuthIdentity'

declare module 'zapatos/custom' {
  export type PgAuthIdentities = AuthIdentity[];  // replace with your custom type or interface as desired
}
