/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import TierEnumType from '../../../graphql/types/TierEnum'

declare module 'zapatos/custom' {
  export type PgTierEnumDomain = TierEnumType;  // replace with your custom type or interface as desired
}
