/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos (v3.3.0), and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';
  import type * as c from 'zapatos/custom';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 101 }

  type JSONSelectableFromSelectable<T> = { [K in keyof T]:
    Date extends T[K] ? Exclude<T[K], Date> | db.DateString :
    Date[] extends T[K] ? Exclude<T[K], Date[]> | db.DateString[] :
    T[K]
  };

  /* === schema: public === */

  /* --- enums --- */

  export type AuthTokenRole = 'su';
  export namespace every {
    export type AuthTokenRole = ['su'];
  }
  export type OrganizationUserAuditEventTypeEnum = 'activated' | 'added' | 'inactivated' | 'removed';
  export namespace every {
    export type OrganizationUserAuditEventTypeEnum = ['activated', 'added', 'inactivated', 'removed'];
  }
  export type TierEnum = 'enterprise' | 'personal' | 'pro';
  export namespace every {
    export type TierEnum = ['enterprise', 'personal', 'pro'];
  }

  /* --- tables --- */

  export namespace OrganizationUserAudit {
    export type Table = 'OrganizationUserAudit';
    export interface Selectable {
      id: number;
      orgId: string;
      userId: string;
      eventDate: Date;
      eventType: OrganizationUserAuditEventTypeEnum;
    }
    export interface Whereable {
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      orgId?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      userId?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      eventDate?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn>;
      eventType?: OrganizationUserAuditEventTypeEnum | db.Parameter<OrganizationUserAuditEventTypeEnum> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, OrganizationUserAuditEventTypeEnum | db.Parameter<OrganizationUserAuditEventTypeEnum> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      orgId: string | db.Parameter<string> | db.SQLFragment;
      userId: string | db.Parameter<string> | db.SQLFragment;
      eventDate: Date | db.Parameter<Date> | db.DateString | db.SQLFragment;
      eventType: OrganizationUserAuditEventTypeEnum | db.Parameter<OrganizationUserAuditEventTypeEnum> | db.SQLFragment;
    }
    export interface Updatable {
      orgId?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      userId?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      eventDate?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment>;
      eventType?: OrganizationUserAuditEventTypeEnum | db.Parameter<OrganizationUserAuditEventTypeEnum> | db.SQLFragment | db.SQLFragment<any, OrganizationUserAuditEventTypeEnum | db.Parameter<OrganizationUserAuditEventTypeEnum> | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'OrganizationUserAudit_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace PgMigrations {
    export type Table = 'PgMigrations';
    export interface Selectable {
      id: number;
      name: string;
      run_on: Date;
    }
    export interface Whereable {
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      run_on?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      name: string | db.Parameter<string> | db.SQLFragment;
      run_on: Date | db.Parameter<Date> | db.DateString | db.SQLFragment;
    }
    export interface Updatable {
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      run_on?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'PgMigrations_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace User {
    export type Table = 'User';
    export interface Selectable {
      id: string;
      email: c.PgEmail;
      createdAt: Date;
      updatedAt: Date;
      inactive: boolean;
      lastSeenAt: Date | null;
      preferredName: string;
      tier: c.PgTierEnumDomain;
      picture: string;
      tms: c.PgStringArray;
      featureFlags: c.PgStringArray;
      identities: c.PgAuthIdentities;
      lastSeenAtURLs: c.PgStringArray | null;
      segmentId: string | null;
      newFeatureId: string | null;
      overLimitCopy: string | null;
      isRemoved: boolean;
      reasonRemoved: string | null;
      rol: c.PgAuthTokenRoleDomain | null;
      payLaterClickCount: number;
    }
    export interface Whereable {
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      email?: c.PgEmail | db.Parameter<c.PgEmail> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, c.PgEmail | db.Parameter<c.PgEmail> | db.SQLFragment | db.ParentColumn>;
      createdAt?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn>;
      updatedAt?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn>;
      inactive?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;
      lastSeenAt?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn>;
      preferredName?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      tier?: c.PgTierEnumDomain | db.Parameter<c.PgTierEnumDomain> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, c.PgTierEnumDomain | db.Parameter<c.PgTierEnumDomain> | db.SQLFragment | db.ParentColumn>;
      picture?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      tms?: c.PgStringArray | db.Parameter<c.PgStringArray> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, c.PgStringArray | db.Parameter<c.PgStringArray> | db.SQLFragment | db.ParentColumn>;
      featureFlags?: c.PgStringArray | db.Parameter<c.PgStringArray> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, c.PgStringArray | db.Parameter<c.PgStringArray> | db.SQLFragment | db.ParentColumn>;
      identities?: c.PgAuthIdentities | db.Parameter<c.PgAuthIdentities> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, c.PgAuthIdentities | db.Parameter<c.PgAuthIdentities> | db.SQLFragment | db.ParentColumn>;
      lastSeenAtURLs?: c.PgStringArray | db.Parameter<c.PgStringArray> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, c.PgStringArray | db.Parameter<c.PgStringArray> | db.SQLFragment | db.ParentColumn>;
      segmentId?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      newFeatureId?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      overLimitCopy?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      isRemoved?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;
      reasonRemoved?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      rol?: c.PgAuthTokenRoleDomain | db.Parameter<c.PgAuthTokenRoleDomain> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, c.PgAuthTokenRoleDomain | db.Parameter<c.PgAuthTokenRoleDomain> | db.SQLFragment | db.ParentColumn>;
      payLaterClickCount?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      id: string | db.Parameter<string> | db.SQLFragment;
      email: c.PgEmail | db.Parameter<c.PgEmail> | db.SQLFragment;
      createdAt: Date | db.Parameter<Date> | db.DateString | db.SQLFragment;
      updatedAt: Date | db.Parameter<Date> | db.DateString | db.SQLFragment;
      inactive?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment;
      lastSeenAt?: Date | db.Parameter<Date> | db.DateString | null | db.DefaultType | db.SQLFragment;
      preferredName: string | db.Parameter<string> | db.SQLFragment;
      tier?: c.PgTierEnumDomain | db.Parameter<c.PgTierEnumDomain> | db.DefaultType | db.SQLFragment;
      picture: string | db.Parameter<string> | db.SQLFragment;
      tms?: c.PgStringArray | db.Parameter<c.PgStringArray> | db.DefaultType | db.SQLFragment;
      featureFlags?: c.PgStringArray | db.Parameter<c.PgStringArray> | db.DefaultType | db.SQLFragment;
      identities?: c.PgAuthIdentities | db.Parameter<c.PgAuthIdentities> | db.DefaultType | db.SQLFragment;
      lastSeenAtURLs?: c.PgStringArray | db.Parameter<c.PgStringArray> | null | db.DefaultType | db.SQLFragment;
      segmentId?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      newFeatureId?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      overLimitCopy?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      isRemoved?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment;
      reasonRemoved?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      rol?: c.PgAuthTokenRoleDomain | db.Parameter<c.PgAuthTokenRoleDomain> | null | db.DefaultType | db.SQLFragment;
      payLaterClickCount?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      id?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      email?: c.PgEmail | db.Parameter<c.PgEmail> | db.SQLFragment | db.SQLFragment<any, c.PgEmail | db.Parameter<c.PgEmail> | db.SQLFragment>;
      createdAt?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment>;
      updatedAt?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment>;
      inactive?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment>;
      lastSeenAt?: Date | db.Parameter<Date> | db.DateString | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | null | db.DefaultType | db.SQLFragment>;
      preferredName?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      tier?: c.PgTierEnumDomain | db.Parameter<c.PgTierEnumDomain> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, c.PgTierEnumDomain | db.Parameter<c.PgTierEnumDomain> | db.DefaultType | db.SQLFragment>;
      picture?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      tms?: c.PgStringArray | db.Parameter<c.PgStringArray> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, c.PgStringArray | db.Parameter<c.PgStringArray> | db.DefaultType | db.SQLFragment>;
      featureFlags?: c.PgStringArray | db.Parameter<c.PgStringArray> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, c.PgStringArray | db.Parameter<c.PgStringArray> | db.DefaultType | db.SQLFragment>;
      identities?: c.PgAuthIdentities | db.Parameter<c.PgAuthIdentities> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, c.PgAuthIdentities | db.Parameter<c.PgAuthIdentities> | db.DefaultType | db.SQLFragment>;
      lastSeenAtURLs?: c.PgStringArray | db.Parameter<c.PgStringArray> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, c.PgStringArray | db.Parameter<c.PgStringArray> | null | db.DefaultType | db.SQLFragment>;
      segmentId?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      newFeatureId?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      overLimitCopy?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      isRemoved?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment>;
      reasonRemoved?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      rol?: c.PgAuthTokenRoleDomain | db.Parameter<c.PgAuthTokenRoleDomain> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, c.PgAuthTokenRoleDomain | db.Parameter<c.PgAuthTokenRoleDomain> | null | db.DefaultType | db.SQLFragment>;
      payLaterClickCount?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'User_pkey' | 'User_email_key';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* === cross-table types === */

  export type Table = OrganizationUserAudit.Table | PgMigrations.Table | User.Table;
  export type Selectable = OrganizationUserAudit.Selectable | PgMigrations.Selectable | User.Selectable;
  export type Whereable = OrganizationUserAudit.Whereable | PgMigrations.Whereable | User.Whereable;
  export type Insertable = OrganizationUserAudit.Insertable | PgMigrations.Insertable | User.Insertable;
  export type Updatable = OrganizationUserAudit.Updatable | PgMigrations.Updatable | User.Updatable;
  export type UniqueIndex = OrganizationUserAudit.UniqueIndex | PgMigrations.UniqueIndex | User.UniqueIndex;
  export type Column = OrganizationUserAudit.Column | PgMigrations.Column | User.Column;
  export type AllTables = [OrganizationUserAudit.Table, PgMigrations.Table, User.Table];
  export type AllMaterializedViews = [];


  export type SelectableForTable<T extends Table> = {
    OrganizationUserAudit: OrganizationUserAudit.Selectable;
    PgMigrations: PgMigrations.Selectable;
    User: User.Selectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    OrganizationUserAudit: OrganizationUserAudit.Whereable;
    PgMigrations: PgMigrations.Whereable;
    User: User.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    OrganizationUserAudit: OrganizationUserAudit.Insertable;
    PgMigrations: PgMigrations.Insertable;
    User: User.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    OrganizationUserAudit: OrganizationUserAudit.Updatable;
    PgMigrations: PgMigrations.Updatable;
    User: User.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    OrganizationUserAudit: OrganizationUserAudit.UniqueIndex;
    PgMigrations: PgMigrations.UniqueIndex;
    User: User.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    OrganizationUserAudit: OrganizationUserAudit.Column;
    PgMigrations: PgMigrations.Column;
    User: User.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    OrganizationUserAudit: OrganizationUserAudit.SQL;
    PgMigrations: PgMigrations.SQL;
    User: User.SQL;
  }[T];

}
